### ISSUE TITLE
Api key header is wrong myst be X-LB-APIKEY X_LB_APIKEY not working anymore

### ISSUE THREAD

**Issue by basd82** [loadbalancer-org/LB_API_Library#1]
https://github.com/loadbalancerorg/LB_API_Library/blob/ec491d5672b459b5b0bda5819517de7a6e38a9c8/jsonapiinterface/curlApiCallInterface.php#L15

The api header now must be X-LB-APIKEY

In the latested version online this version works

**Comment by dpacuszka** [comment]
Sorry for taking so long, but previous maintainer of the repo has left around this time.
Your commit has been merged now, thank you!
